# Generated by Django 5.2.3 on 2025-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_passengerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetails',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
